### PR TITLE
Added alternative approach to fls terms.

### PR DESCRIPTION
**Pull request by iangow**
I think your FLS term lists might be a bit off relative to the original paper.

### CODE REVIEW

**Comment by iangow** [comment]
You don't seem to implement this:

> Sentences with keywords "shall," "should," "can," "could,""may," or "might" are not tagged as forward looking even though they may imply the future. The reason is that these keywords are frequently associated with legal language and uninformative boilerplate disclosures that do not have any real forward-looking connotations. Our excluding such boilerplate language from being classified as forward looking is consistent with the SEC's criticism that firms often provide noninformative boilerplate disclosures and immaterial information in their MD&A (SEC 2003, Li 2010).

This may be fine given the context (conference calls instead of 10-Ks), but you should note this difference.

**Comment by iangow** [comment]
Note that I needed this `[s.strip() for s in terms]` because you seem to have some spaces in `fls_terms2.txt`.

**Comment by yiyangw2** [comment]
Professor Gow, you mentioned that "Note that I needed this [s.strip() for s in terms] because you seem to have some spaces in fls_terms2.txt." But even without this it seems still work. For example, is_forward_looking("next month") still returns True according to current coding.

**Comment by yiyangw2** [comment]
Besides, your definition of time frames contains future 10 years as well, though my original one does not. Professor Gow, I was wondering if you have time on Friday morning 11 am Melbourne time for a Zoom chat for guidance on changing the coding of classification algorithm?

**Comment by iangow** [comment]
The ones with trailing spaces are found in the list below (not all these have trailing spaces, e.g., `are planed` is a spelling issue). ` is_forward_looking("next month")` should not be affected because `'next month'` is not in the list below.

```
['and expect ',
 'and aim ',
 'and anticipate ',
 'and assume ',
 'and commit ',
 'and expect ',
 'and forecast ',
 'and foresee ',
 'and hope ',
 'and intend ',
 'and plan ',
 'is planed',
 'are planed',
 'not planed',
 'is planing',
 'are planing',
 'not planing',
 'and seek ',
 'and project ',
 'and target ']
```

**Comment by iangow** [comment]
> Professor Gow, I was wondering if you have time on Friday morning 11 am Melbourne time for a Zoom chat for guidance on changing the coding of classification algorithm?

Sorry I had another call at that time.

I would suggest refining your measure to use the code I've provided. Ultimately you probably want to put that code in a `.py` file that you import the functions from.

**Comment by iangow** [comment]
> Besides, your definition of time frames contains future 10 years as well, though my original one does not. 

OK. I did not notice that (I was focused on replicating your stats and I guess that this did not affect these).

**Comment by yiyangw2** [comment]
Hi Professor Gow,

  Thank you so much for your guidance and I will do the refining of the measure as suggested! Besides, I will stay with the original definition of time frames to be without future ten years.

Yours sincerely
Yiyang

**Pull request merged**
