### PR TITLE
Added cleaner version of notebook.

### PR DESCRIPTION
**Pull request by iangow**
@yiyangw2 

I made a cleaner version of your notebook.

Does the standard definition of "FLS" include `future_year` the way you have it? Or have you added this?

### CODE REVIEW

**Comment by iangow** [comment]
Why not just use this function?

``` python
def is_forward_looking(sentence:str):
    """Returns whether sentence is forward-looking."""
    return is_term(sentence, create_regex_list(r"fls_terms2.txt"))
```

**Comment by yiyangw2** [comment]
Yes, the original paper also uses 10 future years

**Comment by iangow** [comment]
> Yes, the original paper also uses 10 future years

Which "original paper"?

**Comment by yiyangw2** [comment]
It is Forward-Looking MD&A Disclosures and the Information Environment  https://www.jstor.org/stable/24550655

**Pull request merged**
